[project]
name = "webcam-app"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.1",
    "jinja2>=3.1.6",
    "opencv-python>=4.12.0.88",
    "python-multipart>=0.0.20",
    "ultralytics>=8.3.227",
    "uvicorn>=0.38.0",
]
